spring:
  rabbitmq:
    host: 192.168.239.132
    password: admin
    username: admin
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
